### PR TITLE
Update scs sdk plugin

### PR DESCRIPTION
**Pull request by mwerle**
Updates required to work with latest scs sdk plugin.

Adds no new functionality, but allows other software which uses the updated SCS SDK Plugin to work at the same time.

**GOTCHA:** This change requires a modification to the web javascript due to the way that was implemented.  Now that ets2localradio serves files from your web server instead of using local files, that could be a small headache for people upgrading.

To avoid such gotchas in the future, I would strongly suggest considering modifying the interface between the server and the web clients to instead of passing the entire "ets2data" to just passing the required information (coordinates). This would also significantly reduce the amount of bandwidth required between the server and client(s).

### CODE REVIEW

**Comment by Koenvh1** [comment]
Hi, thank you for updating the SCS plugin - I was not aware that someone had forked the original project. However, I do wonder why you think that this update is worth breaking the current API for. Because how the system currently works, from the moment I merge your pull request, it will take ~30 minutes for all existing v3-installations to break, and I struggle to see how this change would justify that. I do not mean to say that there is no valid reason, but just that I would like to know why you chose this path.

The reason all telemetry data is sent instead of just the required information is twofold: partially because it is easier to implement, but also because from my experience, people are really creative when it comes to adapting software to their needs. That's one of the reasons it is open source, and the `custom.js` file exists (and when it was missing in the first v3 beta, it was requested a lot). The barrier to mess about with some Javascript and see what it does is far lower than recompiling a C# project, hence I do not want to hide information I already have - might as well give you all data to play with.

**Comment by mwerle** [comment]
Sure,  as I already noted, the benefits of upgrading are very little to none for this project.  It's purely a compatibility update so it plays "nicely" with other projects.

I've started working on my own project (it will be a combination voice responder, data logger, and optionally Voice Attack plugin), which uses some of the new data available in this new version of the SCS SDK Plugin /  Shared Memory.  

I'd either need to fork the SCS SDK plugin and create a new Shared Memory region (meaning people need to install and run two plugins with all the overheads that entails), or force people to choose between running either ETS2 Local Radio and this new thing I'm working on.  I'm also not sure whether there's any other clients out there using the new Shared Memory format; I haven't chatted to the devs yet to see what other projects are using their code. 

Personally I find it odd that the Shared Memory region wasn't maintained in a backwards-compatbile manner, but there you go. Maybe that's something to rework and propose to the maintainers instead?

Ultimately it's up to you, of course, and I realise in the short term it will break things for your users. Just thought instead of just sending you a "Feature Request" I'd actually give you the complete feature to decide whether or not to use it.  As for me, I can use my custom-built ETS2 Local Radio as well as the thing I'm working on, so it's not a big deal for me personally either way.

----

I also didn't realise you were exposing all the data for people to do other stuff with. Still, you could leave all of the data on the /api endpoint, and add a new /coordinates (or /radio or whatever) endpoint which you use for the radio.  That way all the data is still available for other people but your radio uses less bandwidth and is less dependent on future data changes.

----

Anyway, thanks for considering and discussing :)

**Comment by Koenvh1** [comment]
> I'd either need to fork the SCS SDK plugin and create a new Shared Memory region (meaning people need to install and run two plugins with all the overheads that entails), or force people to choose between running either ETS2 Local Radio and this new thing I'm working on. 

You don't need to - the original version by @nlhans maps to `Local\SimTelemetryETS2` [1], the one by @RenCloud to `Local\SCSTelemetry` [2]. Sure, everything will be in memory, but it will still work (and the amount of memory used is not that much). You at least don't have to choose between the two. Given that it is not a drop-in replacement, I can understand restructuring the structure. Plus, undoing those changes would break things for other people.

So if I am not mistaken, that means that you can run both version side-by-side, right? (apart from the filename perhaps) Or is there something I am missing that would cause issues? Because otherwise I would rather wait with this until v4, for which I have a couple more plans (like use WebSockets instead of polling, better synchronisation between server and client to make things like #91 easier to implement, using something like Vue.js/React/Angular for the front-end to make updates there smoother and less error-prone).

[1] https://github.com/nlhans/ets2-sdk-plugin/blob/master/ets2-client/C%23/Ets2SdkClient/Ets2SdkTelemetry.cs#L11
[2] https://github.com/RenCloud/scs-sdk-plugin/blob/master/scs-client/C%23/SCSSdkClient/SCSSdkTelemetry.cs#L14

**Comment by mwerle** [comment]
... you are absolutely correct.  I have no idea how I got myself confused there.  I was sure the two versions mapped to the same shared memory region and interfered with each other.

So yeah, apart from the overhead (not so much concerned about the memory, more about the CPU overheads) of running two plugins, please forget my comments about interoperability.

You can keep this pull request for your V4 or delete it as you like.

**Comment by Koenvh1** [comment]
It happens to all of us (or at least to me), and given the similarities (and the fact one is a fork of the other), it is not a strange assumption either. At least I am happy that there are no conflicts. I'll keep this pull request, though I will close it for now.

**Pull request closed without merging**
